#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicSalesApp.Models;

/// <summary>
/// Represents a creator who can upload and sell music on the platform.
/// Creators are onboarded through PayPal Partner Referrals and TaxBandits (W-9/W-8 forms),
/// and can receive payments for their music sales once both onboarding processes are complete.
/// </summary>
public class Creator
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Foreign key to the ApplicationUser who is the creator
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Navigation property to the ApplicationUser
    /// </summary>
    [ForeignKey(nameof(UserId))]
    public virtual ApplicationUser User { get; set; } = null!;

    /// <summary>
    /// PayPal Merchant ID (Payer ID) for the creator's PayPal business account.
    /// This is obtained after successful PayPal onboarding.
    /// </summary>
    [MaxLength(50)]
    public string? PayPalMerchantId { get; set; }

    /// <summary>
    /// The PayPal email address where this creator receives payouts.
    /// This may be different from the creator's login email (User.Email).
    /// Used for PayPal Payouts API calls.
    /// </summary>
    [MaxLength(255)]
    [EmailAddress]
    public string? PayPalEmail { get; set; }

    /// <summary>
    /// The tracking ID used during the Partner Referrals onboarding process.
    /// This is generated by our system and sent to PayPal for tracking.
    /// </summary>
    [MaxLength(100)]
    public string? PayPalTrackingId { get; set; }

    /// <summary>
    /// The referral URL returned by PayPal for the creator to complete onboarding.
    /// </summary>
    [MaxLength(2000)]
    public string? PayPalReferralUrl { get; set; }

    /// <summary>
    /// The status of the creator's PayPal onboarding process.
    /// </summary>
    public CreatorOnboardingStatus OnboardingStatus { get; set; } = CreatorOnboardingStatus.NotStarted;

    /// <summary>
    /// The status of the creator's tax form (W-9/W-8) completion via TaxBandits.
    /// </summary>
    public TaxFormStatus TaxFormStatus { get; set; } = TaxFormStatus.NotStarted;

    /// <summary>
    /// When the creator completed their tax form (W-9/W-8).
    /// </summary>
    public DateTime? TaxFormCompletedAt { get; set; }

    /// <summary>
    /// The PayeeRef used in TaxBandits W-9/W-8 requests.
    /// This is typically the user's email address and is used to correlate webhook callbacks.
    /// </summary>
    [MaxLength(255)]
    public string? TaxBanditsPayeeRef { get; set; }

    /// <summary>
    /// Whether the creator has granted the necessary permissions to the platform.
    /// This is required for multi-party payments.
    /// </summary>
    public bool PaymentsReceivable { get; set; } = false;

    /// <summary>
    /// Whether the creator's email has been confirmed with PayPal.
    /// </summary>
    public bool PrimaryEmailConfirmed { get; set; } = false;

    /// <summary>
    /// Whether the creator has affirmed they have a valid PayPal account in good standing
    /// that can receive payouts. This replaces the business account onboarding flow.
    /// If false, the creator will not receive royalty payouts.
    /// </summary>
    public bool PayPalAccountAffirmed { get; set; } = false;

    /// <summary>
    /// The rate paid per stream in USD (e.g., 0.005 for $5 per 1000 streams).
    /// This is set when the creator is onboarded and locked in for the lifetime of the creator account.
    /// </summary>
    [Column(TypeName = "decimal(10,6)")]
    public decimal StreamPayRate { get; set; } = 0.005m;

    /// <summary>
    /// Display name for the creator (can be different from username).
    /// </summary>
    [MaxLength(200)]
    public string? DisplayName { get; set; }

    /// <summary>
    /// Optional bio or description for the creator.
    /// </summary>
    [MaxLength(1000)]
    public string? Bio { get; set; }

    /// <summary>
    /// When the creator record was created.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When the creator completed PayPal onboarding.
    /// </summary>
    public DateTime? OnboardedAt { get; set; }

    /// <summary>
    /// When the creator record was last updated.
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Whether the creator account is currently active and can sell music.
    /// When set to false, the creator's music will not be available in the Music Library or playlists.
    /// </summary>
    public bool IsActive { get; set; } = false;

    /// <summary>
    /// Checks if both PayPal and tax form onboarding are complete.
    /// </summary>
    [NotMapped]
    public bool IsFullyOnboarded => OnboardingStatus == CreatorOnboardingStatus.Completed 
                                    && TaxFormStatus == TaxFormStatus.Completed;
}

/// <summary>
/// Represents the status of a creator's PayPal onboarding process.
/// </summary>
public enum CreatorOnboardingStatus
{
    /// <summary>
    /// Onboarding has not been started.
    /// </summary>
    NotStarted = 0,

    /// <summary>
    /// Referral link has been generated, waiting for creator to complete PayPal signup.
    /// </summary>
    Pending = 1,

    /// <summary>
    /// Creator has completed PayPal signup but additional verification may be needed.
    /// </summary>
    InProgress = 2,

    /// <summary>
    /// Creator has completed onboarding and can receive payments.
    /// </summary>
    Completed = 3,

    /// <summary>
    /// Onboarding was declined or failed.
    /// </summary>
    Failed = 4,

    /// <summary>
    /// Creator account has been suspended.
    /// </summary>
    Suspended = 5,

    /// <summary>
    /// Creator has revoked their consent to the platform via PayPal.
    /// This typically happens when the creator removes the platform's permissions in their PayPal account.
    /// </summary>
    ConsentRevoked = 6
}

/// <summary>
/// Represents the status of a creator's tax form (W-9/W-8BEN) completion via TaxBandits.
/// </summary>
public enum TaxFormStatus
{
    /// <summary>
    /// Tax form has not been started or requested.
    /// </summary>
    NotStarted = 0,

    /// <summary>
    /// Tax form request has been sent, waiting for creator to complete it.
    /// </summary>
    Pending = 1,

    /// <summary>
    /// Tax form has been completed successfully.
    /// </summary>
    Completed = 2,

    /// <summary>
    /// Tax form submission failed or was rejected.
    /// </summary>
    Failed = 3
}
