#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MusicSalesApp.Models;

/// <summary>
/// Represents a seller who can upload and sell music on the platform.
/// Sellers are onboarded through PayPal Partner Referrals and can receive payments for their music sales.
/// </summary>
public class Seller
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// Foreign key to the ApplicationUser who is the seller
    /// </summary>
    public int UserId { get; set; }

    /// <summary>
    /// Navigation property to the ApplicationUser
    /// </summary>
    [ForeignKey(nameof(UserId))]
    public virtual ApplicationUser User { get; set; } = null!;

    /// <summary>
    /// PayPal Merchant ID (Payer ID) for the seller's PayPal business account.
    /// This is obtained after successful PayPal onboarding.
    /// </summary>
    [MaxLength(50)]
    public string? PayPalMerchantId { get; set; }

    /// <summary>
    /// The tracking ID used during the Partner Referrals onboarding process.
    /// This is generated by our system and sent to PayPal for tracking.
    /// </summary>
    [MaxLength(100)]
    public string? PayPalTrackingId { get; set; }

    /// <summary>
    /// The referral URL returned by PayPal for the seller to complete onboarding.
    /// </summary>
    [MaxLength(2000)]
    public string? PayPalReferralUrl { get; set; }

    /// <summary>
    /// The status of the seller's PayPal onboarding process.
    /// </summary>
    public SellerOnboardingStatus OnboardingStatus { get; set; } = SellerOnboardingStatus.NotStarted;

    /// <summary>
    /// Whether the seller has granted the necessary permissions to the platform.
    /// This is required for multi-party payments.
    /// </summary>
    public bool PaymentsReceivable { get; set; } = false;

    /// <summary>
    /// Whether the seller's email has been confirmed with PayPal.
    /// </summary>
    public bool PrimaryEmailConfirmed { get; set; } = false;

    /// <summary>
    /// The commission percentage that the platform takes from each sale.
    /// Default is 15% (0.15).
    /// </summary>
    [Column(TypeName = "decimal(5,4)")]
    public decimal CommissionRate { get; set; } = 0.15m;

    /// <summary>
    /// The rate paid per stream in USD (e.g., 0.005 for $5 per 1000 streams).
    /// This is set when the seller is onboarded and locked in for the lifetime of the seller account.
    /// </summary>
    [Column(TypeName = "decimal(10,6)")]
    public decimal StreamPayRate { get; set; } = 0.005m;

    /// <summary>
    /// Display name for the seller (can be different from username).
    /// </summary>
    [MaxLength(200)]
    public string? DisplayName { get; set; }

    /// <summary>
    /// Optional bio or description for the seller.
    /// </summary>
    [MaxLength(1000)]
    public string? Bio { get; set; }

    /// <summary>
    /// When the seller record was created.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When the seller completed PayPal onboarding.
    /// </summary>
    public DateTime? OnboardedAt { get; set; }

    /// <summary>
    /// When the seller record was last updated.
    /// </summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Whether the seller account is currently active and can sell music.
    /// </summary>
    public bool IsActive { get; set; } = false;
}

/// <summary>
/// Represents the status of a seller's PayPal onboarding process.
/// </summary>
public enum SellerOnboardingStatus
{
    /// <summary>
    /// Onboarding has not been started.
    /// </summary>
    NotStarted = 0,

    /// <summary>
    /// Referral link has been generated, waiting for seller to complete PayPal signup.
    /// </summary>
    Pending = 1,

    /// <summary>
    /// Seller has completed PayPal signup but additional verification may be needed.
    /// </summary>
    InProgress = 2,

    /// <summary>
    /// Seller has completed onboarding and can receive payments.
    /// </summary>
    Completed = 3,

    /// <summary>
    /// Onboarding was declined or failed.
    /// </summary>
    Failed = 4,

    /// <summary>
    /// Seller account has been suspended.
    /// </summary>
    Suspended = 5,

    /// <summary>
    /// Seller has revoked their consent to the platform via PayPal.
    /// This typically happens when the seller removes the platform's permissions in their PayPal account.
    /// </summary>
    ConsentRevoked = 6
}
