#nullable enable
using Hangfire;
using MusicSalesApp.Models;

namespace MusicSalesApp.Services;

/// <summary>
/// Telling followers that an artist they follow has released something.
/// </summary>
/// <remarks>
/// Release notifications are generated by StreamTunes, never composed or triggered by a creator.
/// That is what keeps the feature from becoming a mailing list: a creator's only lever is
/// publishing music, and the platform decides who hears about it and how.
/// </remarks>
public interface IArtistReleaseNotificationService
{
    /// <summary>
    /// Stamps newly-public songs with their release time and creates the in-app notification rows
    /// for eligible followers. The hourly Hangfire job.
    /// </summary>
    /// <returns>The number of notification rows created.</returns>
    // Hangfire resolves filters from Job.Method, which for an interface-registered job is
    // this declaration. The same attribute on the implementation is silently ignored.
    //
    // This one is pure database work and normally finishes in well under a second, but it is also
    // the job whose double-run would be most visible, so the lock is cheap insurance. The unique
    // index would catch a duplicate anyway; this avoids the wasted work and the noisy exception.
    [DisableConcurrentExecution(timeoutInSeconds: 300)]
    [AutomaticRetry(Attempts = 0)]
    Task<int> CreatePendingNotificationsAsync();

    /// <summary>
    /// Emails the notifications that have not been emailed yet, to listeners who want them.
    /// The nightly Hangfire job.
    /// </summary>
    /// <returns>The number of emails successfully sent.</returns>
    // Hangfire resolves filters from Job.Method, which for an interface-registered job is
    // this declaration. The same attribute on the implementation is silently ignored.
    //
    // At five seconds a message plus a minute between batches, a popular release can keep this
    // running for hours - well past the point where tomorrow's run would start. AutomaticRetry(0)
    // is required alongside because DisableConcurrentExecution throws on lock timeout.
    [DisableConcurrentExecution(timeoutInSeconds: 3600)]
    [AutomaticRetry(Attempts = 0)]
    Task<int> SendPendingEmailsAsync();

    /// <summary>
    /// The listener's release notifications, newest first.
    /// </summary>
    Task<IReadOnlyList<ArtistReleaseNotificationDto>> GetForListenerAsync(
        int listenerUserId,
        CancellationToken cancellationToken = default);

    Task<int> GetUnreadCountAsync(int listenerUserId, CancellationToken cancellationToken = default);

    Task<bool> MarkReadAsync(int notificationId, int listenerUserId, CancellationToken cancellationToken = default);
}
